FROM gcc:latest

RUN apt-get update && apt-get install -y cmake

COPY . /usr/src/mytest

WORKDIR /usr/src/mytest

RUN mkdir build
WORKDIR /usr/src/mytest/build

RUN cmake .. && make

# Run the tests
CMD ["sh", "-c", "./runTestsAdd && ./runTestsGet && ./runTestsSearch && ./runTestsDeleteCommand && ./runTestsCompressor && ./runTestsStorage && ./runTestsConstStorageDispatcher && ./runTestsThreadPerClientDispatcher"]
